# Generated by Django 4.0.1 on 2022-03-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_destinationtransportation_destinationaccomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationaccomodation',
            name='destination_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destinationtransportation',
            name='destination_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
