# Generated by Django 4.0.4 on 2022-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_destinationaccomodation_destination_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekguides',
            name='guide_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
