# Generated by Django 4.0.4 on 2022-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_destination_destination_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='accomodation_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transportation_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trekguides',
            name='guide_description',
            field=models.TextField(blank=True),
        ),
    ]
