# Generated by Django 4.0.4 on 2022-05-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0007_alter_accomodation_accomodation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destination_latitude',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_longitude',
            field=models.FloatField(max_length=30),
        ),
    ]
