# Generated by Django 4.0.4 on 2022-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0008_alter_destination_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_days',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
