# Generated by Django 4.0.4 on 2022-05-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0009_destination_destination_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='destination_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datas.destination'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DestinationAccomodation',
        ),
    ]
