# Generated by Django 4.0.4 on 2022-05-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0010_accomodation_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='package_contact',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_date',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_time',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
