# Generated by Django 4.0.4 on 2022-05-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0011_packages_package_contact_packages_package_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='package_days',
        ),
    ]
