# Generated by Django 4.0.4 on 2022-05-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0012_remove_packages_package_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekguides',
            name='guide_email',
        ),
    ]
