# Generated by Django 4.0.4 on 2022-06-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0013_remove_trekguides_guide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='destination_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datas.destination'),
            preserve_default=False,
        ),
    ]
