# Generated by Django 4.0.4 on 2022-06-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0014_transportation_destination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='datas.destination'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='datas.destination'),
        ),
    ]
