# Generated by Django 4.0.1 on 2022-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekguides',
            name='guide_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
