# Generated by Django 4.0.1 on 2022-03-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_data', '0002_alter_trekguides_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekguides',
            name='guide_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
